### ISSUE TITLE
it doesnt simulate on onChange event after changing focus from the field receving value from sendkeys

### ISSUE THREAD

**Issue by prachi02** [featurist/jquery-sendkeys#1]
jQuery code:
$(".outputselected").sendkeys('1234')
$(".outputfocus").focus();

There is an onChange event or trigger on field ..outputselected. It doesnt get fired

webtrigger OnChange      ; trigger will be executed in the browser
 javascript                           ; implementation code is JavaScript
alert("hello");

 endjavascript
end; onchange

**Comment by refractalize** [comment]
Hi @prachi02 you may be better speaking to the guy who wrote this, from this blog post: http://bililite.com/blog/2011/01/23/improved-sendkeys/

The other thing to note is that I rewrote sendkeys in [browser-monkey](https://github.com/featurist/browser-monkey), [here](https://github.com/featurist/browser-monkey/blob/master/sendkeys.js). It does have send a change event, so this might help. If you're using `jquery-sendkeys` to test your JS and DOM code, then I strongly suggest you check out [browser-monkey](https://github.com/featurist/browser-monkey).

**Comment by prachi02** [comment]
Hi@refractalize......Can you explain me how to use it .......

**Comment by refractalize** [comment]
oh, you mean the sendkeys in browser-monkey? You might have to copy/paste that code into your project and make it work...

**Comment by refractalize** [comment]
what are you trying to do, perhaps I can help?

**Comment by prachi02** [comment]
First I am trying
1. I did npm install browser-monkey
2. Now I already have a javascript framework where I want to use browser monkey
3.My question is ,If i want to include browser monkey framework into mine.Can I include all js file using  <script > tag ??...

**Comment by refractalize** [comment]
browser-monkey is for running unit tests against your DOM/JS code. In your test, you write some code to setup your DOM and your JS app, then you can use browser-monkey to click buttons, enter text and then test DOM elements. You can use browserify to `require('browser-monkey');` into your JS file. See this [example](https://github.com/dereke/web-testing).

**Comment by prachi02** [comment]
I wanted to use ...the piece of code of send keys....If I copy and paste that in for of sendkeys.js and include that in form of script tag in my project.....and den use the the api ...element.sendkeys("text").......i think in this way its not possible

**Comment by refractalize** [comment]
This will set a global function called `sendkeys`, you can include this in a `<script>` tag to use it.

Then you can write `sendkeys(element, 'some text')`.

``` js
(function () {
  function dispatchEvent(el, type, char) {
    var event = document.createEvent("Events");
    event.initEvent(type, true, false);
    event.charCode = char;
    el.dispatchEvent(event);
  }

  function sendkey(el, char) {
    dispatchEvent(el, "keydown", char);
    dispatchEvent(el, "keyup", char);
    dispatchEvent(el, "keypress", char);
    dispatchEvent(el, "input");
  }

  function sendkeys(el, text) {
    el.focus();
    if (el.setActive) {
      el.setActive();
    }

    var originalValue = el.value;

    if (text.length === 0) {
      sendkey(el, '');
      el.value = '';
    } else {
      for (var n = 0; n < text.length; ++n) {
        var char = text[n];
        el.value = text.substring(0, n + 1);
        sendkey(el, char);
      }
    }

    if (originalValue !== text){
      dispatchEvent(el, 'change');
    }
  };

  sendkeys.html = function(el, html) {
    el.innerHTML = html;
    dispatchEvent(el, "input");
  };

  window.sendkeys = sendkeys;
})();
```

**Comment by prachi02** [comment]
I tried this ..but I am getting this error while I am trying to use .Sendkeys() as a function.
I have attached the error message. Are there any more dependency??

![dispatchevent](https://cloud.githubusercontent.com/assets/12513978/10216401/0f4b0974-6829-11e5-9997-4820b13dc6e3.png)
