### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by xaolas** [featurist/jquery-sendkeys#2]
Please update to Version: 4 https://github.com/dwachss/bililiteRange/blob/master/jquery.sendkeys.js

**Comment by refractalize** [comment]
Hi @xaolas, no problem. I'm not really staying on top of this, so I'm happy to give you contributor rights to this repo and the NPM module, if you want it?

**Comment by refractalize** [comment]
v4 released now

**Comment by xaolas** [comment]
Yes, I want. Thx.

**Comment by refractalize** [comment]
I've added you as a collaborator - do you have an NPM username? I'll add you as collaborator on that too.
